using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using USBUnlocker.Utilities;

namespace USBUnlocker.Core
{
    // =====================================================================
    // CAPABILITY METADATA
    // =====================================================================
    
    public enum CapabilityType
    {
        Diagnostic,
        Repair,
        Report,
        Export,
        Tool,
        Workflow,
        Settings,
        Utility
    }
    
    public enum RiskLevel
    {
        Safe,
        Moderate,
        Dangerous
    }
    
    public class Capability
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public CapabilityType Type { get; set; }
        public Action Action { get; set; }
        public bool AdminRequired { get; set; }
        public bool Available { get; set; } = true;
        public List<string> Dependencies { get; set; } = new List<string>();
        public RiskLevel Risk { get; set; } = RiskLevel.Safe;
        public int Order { get; set; }
        public FeatureStatus Status { get; set; }
        public bool IsContextAction { get; set; }
        public Func<bool> ContextCondition { get; set; }
    }
    
    public enum FeatureStatus
    {
        Ready,
        RequiresAdmin,
        Unavailable,
        Error
    }
    
    // =====================================================================
    // WORKFLOW
    // =====================================================================
    
    public class WorkflowStep
    {
        public string CapabilityId { get; set; }
        public string Description { get; set; }
        public bool RequiresConfirmation { get; set; }
    }
    
    public class Workflow
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public List<WorkflowStep> Steps { get; set; } = new List<WorkflowStep>();
        public bool AdminRequired { get; set; }
        public RiskLevel Risk { get; set; } = RiskLevel.Safe;
        public bool AutoGenerated { get; set; }
        public int Order { get; set; }
    }
    
    // =====================================================================
    // CAPABILITY REGISTRY — Single source of truth
    // =====================================================================
    
    public class FeatureRegistry
    {
        private readonly List<Capability> _capabilities = new List<Capability>();
        private readonly List<Workflow> _workflows = new List<Workflow>();
        private readonly Dictionary<int, object> _menuMap = new Dictionary<int, object>();
        private int _menuNumber = 0;
        private readonly AppConfig _config;
        
        // Context state
        private bool _lastScanHadIssues = false;
        private bool _lastScanHadRepair = false;
        
        public int CapabilityCount => _capabilities.Count;
        public int AvailableCount => _capabilities.Count(c => c.Available && c.Status != FeatureStatus.Unavailable);
        public int UnavailableCount => _capabilities.Count(c => !c.Available || c.Status == FeatureStatus.Unavailable);
        public int WorkflowCount => _workflows.Count;
        public int CategoryCount => _capabilities.Select(c => c.Category).Distinct().Count();
        
        public FeatureRegistry(AppConfig config)
        {
            _config = config;
        }
        
        // =================================================================
        // REGISTRATION
        // =================================================================
        
        public void Register(Capability capability)
        {
            if (capability == null || string.IsNullOrEmpty(capability.Id))
                return;
            
            // Prevent duplicates
            if (_capabilities.Any(c => c.Id == capability.Id))
                return;
            
            _capabilities.Add(capability);
        }
        
        public void RegisterWorkflow(Workflow workflow)
        {
            if (workflow == null || string.IsNullOrEmpty(workflow.Id))
                return;
            
            if (_workflows.Any(w => w.Id == workflow.Id))
                return;
            
            _workflows.Add(workflow);
        }
        
        // =================================================================
        // AVAILABILITY CHECK
        // =================================================================
        
        public void CheckAvailability()
        {
            bool isAdmin = AdminHelper.IsAdministrator();
            
            foreach (var cap in _capabilities)
            {
                // Check admin requirement
                if (cap.AdminRequired && !isAdmin)
                    cap.Status = FeatureStatus.RequiresAdmin;
                else if (!cap.Available)
                    cap.Status = FeatureStatus.Unavailable;
                else
                    cap.Status = FeatureStatus.Ready;
                
                // Check dependencies
                if (cap.Dependencies.Count > 0)
                {
                    foreach (var depId in cap.Dependencies)
                    {
                        var dep = _capabilities.FirstOrDefault(c => c.Id == depId);
                        if (dep != null && dep.Status != FeatureStatus.Ready)
                        {
                            cap.Status = FeatureStatus.Unavailable;
                            break;
                        }
                    }
                }
            }
        }
        
        // =================================================================
        // DYNAMIC MENU BUILDER
        // =================================================================
        
        public void BuildMenu()
        {
            _menuMap.Clear();
            _menuNumber = 0;
            
            // Discover categories dynamically from capabilities
            var categories = _capabilities
                .GroupBy(c => c.Category)
                .OrderBy(g => g.Min(c => c.Order))
                .ToList();
            
            foreach (var category in categories)
            {
                var availableCaps = category
                    .Where(c => !c.IsContextAction)
                    .OrderBy(c => c.Order)
                    .ToList();
                
                if (availableCaps.Count == 0)
                    continue;
                
                // Category header
                Console.WriteLine();
                Console.WriteLine("------------------------------------------------------------");
                Console.WriteLine(category.Key);
                Console.WriteLine("------------------------------------------------------------");
                
                // List capabilities
                foreach (var cap in availableCaps)
                {
                    _menuNumber++;
                    _menuMap[_menuNumber] = cap;
                    
                    string statusLabel = GetStatusLabel(cap.Status);
                    string paddedNum = _menuNumber.ToString().PadLeft(2);
                    string adminTag = cap.AdminRequired ? "" : "";
                    
                    Console.WriteLine($" [{paddedNum}] {cap.Name,-30} [{statusLabel}]");
                }
            }
            
            // Auto-generated workflows section
            var autoWorkflows = _workflows.Where(w => w.AutoGenerated).ToList();
            if (autoWorkflows.Count > 0)
            {
                Console.WriteLine();
                Console.WriteLine("------------------------------------------------------------");
                Console.WriteLine("AUTO WORKFLOWS");
                Console.WriteLine("------------------------------------------------------------");
                
                foreach (var wf in autoWorkflows.OrderBy(w => w.Order))
                {
                    _menuNumber++;
                    _menuMap[_menuNumber] = wf;
                    
                    string paddedNum = _menuNumber.ToString().PadLeft(2);
                    string statusLabel = wf.AdminRequired ? "REQUIRES ADMIN" : "READY";
                    Console.WriteLine($" [{paddedNum}] {wf.Name,-30} [{statusLabel}]");
                }
            }
            
            // Context actions (only show when relevant)
            var contextActions = _capabilities
                .Where(c => c.IsContextAction && c.ContextCondition != null && c.ContextCondition())
                .OrderBy(c => c.Order)
                .ToList();
            
            if (contextActions.Count > 0)
            {
                Console.WriteLine();
                Console.WriteLine("------------------------------------------------------------");
                Console.WriteLine("CONTEXT ACTIONS");
                Console.WriteLine("------------------------------------------------------------");
                
                foreach (var cap in contextActions)
                {
                    _menuNumber++;
                    _menuMap[_menuNumber] = cap;
                    
                    string paddedNum = _menuNumber.ToString().PadLeft(2);
                    Console.WriteLine($" [{paddedNum}] {cap.Name,-30} [READY]");
                }
            }
            
            // Footer with keyboard shortcuts
            Console.WriteLine();
            Console.WriteLine("------------------------------------------------------------");
            Console.WriteLine(" [S] Search    [W] Workflows    [I] Inspector");
            Console.WriteLine(" [H] Help      [R] Refresh      [Q] Exit");
            Console.WriteLine("------------------------------------------------------------");
        }
        
        // =================================================================
        // DISPATCH
        // =================================================================
        
        public void Dispatch(string input)
        {
            if (string.IsNullOrEmpty(input))
                return;
            
            // Validate numeric input
            if (!int.TryParse(input, out int menuNum))
            {
                ShowInvalidSelection();
                return;
            }
            
            if (menuNum < 1 || menuNum > _menuNumber)
            {
                ShowInvalidSelection();
                return;
            }
            
            object target = _menuMap[menuNum];
            
            if (target is Capability cap)
            {
                DispatchCapability(cap);
            }
            else if (target is Workflow wf)
            {
                DispatchWorkflow(wf);
            }
        }
        
        private void DispatchCapability(Capability cap)
        {
            if (cap.Status == FeatureStatus.RequiresAdmin)
            {
                ShowAdminRequired(cap.Name);
                return;
            }
            
            if (cap.Status == FeatureStatus.Unavailable)
            {
                ShowUnavailable(cap.Name);
                return;
            }
            
            try
            {
                cap.Action?.Invoke();
            }
            catch (Exception ex)
            {
                Logger.Error($"Feature {cap.Id} failed: {ex.Message}");
                Console.WriteLine($"\nFeature: {cap.Name}");
                Console.WriteLine("Status: FAILED");
                Console.WriteLine($"Error: {ex.Message}");
            }
            
            DisplayHelper.PauseReturnToMenu();
        }
        
        private void DispatchWorkflow(Workflow wf)
        {
            if (wf.AdminRequired && !AdminHelper.IsAdministrator())
            {
                ShowAdminRequired(wf.Name);
                return;
            }
            
            Console.WriteLine($"\n============================================================");
            Console.WriteLine($"  WORKFLOW: {wf.Name}");
            Console.WriteLine($"============================================================");
            Console.WriteLine($"\n{wf.Description}");
            Console.WriteLine($"\nSteps: {wf.Steps.Count}");
            Console.WriteLine($"\nThis will execute multiple operations.");
            
            if (wf.Risk == RiskLevel.Dangerous || wf.Risk == RiskLevel.Moderate)
            {
                Console.WriteLine($"\n⚠ Risk Level: {wf.Risk.ToString().ToUpper()}");
            }
            
            Console.WriteLine("\nContinue?");
            Console.WriteLine("[Y] Yes");
            Console.WriteLine("[N] No");
            Console.Write("\nChoice: ");
            
            string confirm = Console.ReadLine();
            if (confirm == null || confirm.ToUpper() != "Y")
                return;
            
            ExecuteWorkflow(wf);
            DisplayHelper.PauseReturnToMenu();
        }
        
        private void ExecuteWorkflow(Workflow wf)
        {
            int stepNum = 0;
            int total = wf.Steps.Count;
            
            foreach (var step in wf.Steps)
            {
                stepNum++;
                var cap = _capabilities.FirstOrDefault(c => c.Id == step.CapabilityId);
                
                if (cap == null)
                {
                    Console.WriteLine($"\n[{stepNum}/{total}] SKIPPED: {step.Description} (capability not found)");
                    continue;
                }
                
                if (cap.Status == FeatureStatus.Unavailable)
                {
                    Console.WriteLine($"\n[{stepNum}/{total}] SKIPPED: {step.Description} (unavailable)");
                    continue;
                }
                
                if (cap.Status == FeatureStatus.RequiresAdmin)
                {
                    Console.WriteLine($"\n[{stepNum}/{total}] SKIPPED: {step.Description} (requires admin)");
                    continue;
                }
                
                Console.WriteLine($"\n[{stepNum}/{total}] {step.Description}...");
                
                try
                {
                    cap.Action?.Invoke();
                    Logger.Success($"Workflow step {stepNum}: {cap.Name} completed");
                }
                catch (Exception ex)
                {
                    Logger.Error($"Workflow step {stepNum}: {cap.Name} failed: {ex.Message}");
                    Console.WriteLine($"  Error: {ex.Message}");
                }
            }
            
            Console.WriteLine("\n============================================================");
            Console.WriteLine("WORKFLOW COMPLETE");
            Console.WriteLine("============================================================");
        }
        
        // =================================================================
        // SEARCH
        // =================================================================
        
        public void Search(string query)
        {
            if (string.IsNullOrWhiteSpace(query))
            {
                Console.WriteLine("Usage: search <keyword>");
                return;
            }
            
            string lower = query.ToLower();
            var results = _capabilities
                .Where(c => c.Name.ToLower().Contains(lower) ||
                           c.Description.ToLower().Contains(lower) ||
                           c.Category.ToLower().Contains(lower) ||
                           c.Id.ToLower().Contains(lower))
                .OrderBy(c => c.Order)
                .ToList();
            
            Console.WriteLine("\n============================================================");
            Console.WriteLine($"  SEARCH: \"{query}\"");
            Console.WriteLine("============================================================");
            
            if (results.Count == 0)
            {
                Console.WriteLine("\nNo capabilities found matching your search.");
            }
            else
            {
                Console.WriteLine($"\nFound {results.Count} matching capabilities:\n");
                
                int num = 0;
                foreach (var cap in results)
                {
                    num++;
                    string statusLabel = GetStatusLabel(cap.Status);
                    Console.WriteLine($"  [{num}] {cap.Name}");
                    Console.WriteLine($"      Category: {cap.Category} | Type: {cap.Type} | Status: {statusLabel}");
                    Console.WriteLine($"      {cap.Description}");
                    Console.WriteLine();
                }
            }
            
            Console.WriteLine("============================================================");
        }
        
        // =================================================================
        // HELP (dynamic from registry)
        // =================================================================
        
        public void DisplayHelp()
        {
            Console.WriteLine("\n============================================================");
            Console.WriteLine("  HELP — Heavenly Keys v3.0");
            Console.WriteLine("============================================================");
            
            // Group by category dynamically
            var categories = _capabilities
                .GroupBy(c => c.Category)
                .OrderBy(g => g.Min(c => c.Order))
                .ToList();
            
            foreach (var category in categories)
            {
                Console.WriteLine($"\n--- {category.Key} ---\n");
                
                foreach (var cap in category.OrderBy(c => c.Order))
                {
                    string statusLabel = GetStatusLabel(cap.Status);
                    Console.WriteLine($"  {cap.Name} [{statusLabel}]");
                    Console.WriteLine($"      {cap.Description}");
                    Console.WriteLine($"      Type: {cap.Type} | Risk: {cap.Risk}");
                    if (cap.AdminRequired)
                        Console.WriteLine($"      Requires Administrator: Yes");
                    if (cap.Dependencies.Count > 0)
                        Console.WriteLine($"      Dependencies: {string.Join(", ", cap.Dependencies)}");
                    Console.WriteLine();
                }
            }
            
            // Workflows
            if (_workflows.Count > 0)
            {
                Console.WriteLine("--- WORKFLOWS ---\n");
                
                foreach (var wf in _workflows.OrderBy(w => w.Order))
                {
                    string source = wf.AutoGenerated ? " (auto-generated)" : "";
                    Console.WriteLine($"  {wf.Name}{source}");
                    Console.WriteLine($"      {wf.Description}");
                    Console.WriteLine($"      Steps: {wf.Steps.Count} | Risk: {wf.Risk}");
                    Console.WriteLine();
                }
            }
            
            Console.WriteLine("--- KEYBOARD SHORTCUTS ---\n");
            Console.WriteLine("  [S] Search    Search capabilities by keyword");
            Console.WriteLine("  [W] Workflows View available workflows");
            Console.WriteLine("  [I] Inspector View capability details (debug)");
            Console.WriteLine("  [H] Help      Show this help screen");
            Console.WriteLine("  [R] Refresh   Refresh menu and capabilities");
            Console.WriteLine("  [Q] Exit      Exit USBUnlocker");
            Console.WriteLine();
            Console.WriteLine("============================================================");
        }
        
        // =================================================================
        // WORKFLOWS LIST
        // =================================================================
        
        public void DisplayWorkflows()
        {
            Console.WriteLine("\n============================================================");
            Console.WriteLine("  AVAILABLE WORKFLOWS");
            Console.WriteLine("============================================================");
            
            if (_workflows.Count == 0)
            {
                Console.WriteLine("\nNo workflows available.");
            }
            else
            {
                foreach (var wf in _workflows.OrderBy(w => w.Order))
                {
                    string source = wf.AutoGenerated ? " [AUTO]" : "";
                    string risk = wf.Risk != RiskLevel.Safe ? $" ⚠ {wf.Risk}" : "";
                    Console.WriteLine($"\n  {wf.Name}{source}{risk}");
                    Console.WriteLine($"  {wf.Description}");
                    Console.WriteLine($"  Steps:");
                    
                    foreach (var step in wf.Steps)
                    {
                        var cap = _capabilities.FirstOrDefault(c => c.Id == step.CapabilityId);
                        string stepStatus = cap != null && cap.Status == FeatureStatus.Ready ? "✓" : "✗";
                        Console.WriteLine($"    {stepStatus} {step.Description}");
                    }
                }
            }
            
            Console.WriteLine("\n============================================================");
        }
        
        // =================================================================
        // CAPABILITY INSPECTOR (debug/technician mode)
        // =================================================================
        
        public void DisplayInspector()
        {
            Console.WriteLine("\n============================================================");
            Console.WriteLine("  CAPABILITY INSPECTOR");
            Console.WriteLine("============================================================");
            
            Console.WriteLine($"\n  Capabilities discovered: {_capabilities.Count}");
            Console.WriteLine($"  Available:              {AvailableCount}");
            Console.WriteLine($"  Unavailable:            {UnavailableCount}");
            Console.WriteLine($"  Workflows:              {_workflows.Count}");
            Console.WriteLine($"  Categories:             {CategoryCount}");
            
            // Category breakdown
            Console.WriteLine("\n  --- Category Breakdown ---\n");
            var catGroups = _capabilities.GroupBy(c => c.Category).OrderBy(g => g.Key);
            foreach (var g in catGroups)
            {
                int ready = g.Count(c => c.Status == FeatureStatus.Ready);
                int admin = g.Count(c => c.Status == FeatureStatus.RequiresAdmin);
                int unavail = g.Count(c => c.Status == FeatureStatus.Unavailable);
                Console.WriteLine($"  {g.Key,-15} Total: {g.Count(),-3}  Ready: {ready,-3}  Admin: {admin,-3}  Unavail: {unavail}");
            }
            
            // All capabilities
            Console.WriteLine("\n  --- All Capabilities ---\n");
            Console.WriteLine($"  {"ID",-14} {"Name",-30} {"Category",-12} {"Type",-11} {"Status",-15} {"Admin"}");
            Console.WriteLine($"  {new string('-', 100)}");
            
            foreach (var cap in _capabilities.OrderBy(c => c.Order))
            {
                string statusLabel = GetStatusLabel(cap.Status);
                string admin = cap.AdminRequired ? "YES" : "no";
                Console.WriteLine($"  {cap.Id,-14} {cap.Name,-30} {cap.Category,-12} {cap.Type,-11} {statusLabel,-15} {admin}");
                
                if (cap.Dependencies.Count > 0)
                    Console.WriteLine($"  {"",14} Dependencies: {string.Join(", ", cap.Dependencies)}");
                if (!string.IsNullOrEmpty(cap.Description))
                    Console.WriteLine($"  {"",14} {cap.Description}");
            }
            
            // Workflows detail
            if (_workflows.Count > 0)
            {
                Console.WriteLine("\n  --- Workflows ---\n");
                foreach (var wf in _workflows.OrderBy(w => w.Order))
                {
                    string source = wf.AutoGenerated ? " [AUTO]" : "";
                    Console.WriteLine($"  {wf.Id}: {wf.Name}{source}");
                    Console.WriteLine($"    {wf.Description}");
                    Console.WriteLine($"    Steps: {wf.Steps.Count} | Risk: {wf.Risk} | Admin: {(wf.AdminRequired ? "YES" : "no")}");
                }
            }
            
            Console.WriteLine("\n============================================================");
        }
        
        // =================================================================
        // AUTO-GENERATE WORKFLOWS from capabilities
        // =================================================================
        
        public void AutoGenerateWorkflows()
        {
            _workflows.RemoveAll(w => w.AutoGenerated);
            
            // Auto-generate: Full Diagnostic (all safe diagnostics)
            var diagnostics = _capabilities
                .Where(c => c.Type == CapabilityType.Diagnostic && c.Risk == RiskLevel.Safe && c.Available && c.Status != FeatureStatus.Unavailable)
                .OrderBy(c => c.Order)
                .ToList();
            
            if (diagnostics.Count >= 3)
            {
                var wf = new Workflow
                {
                    Id = "AUTO_DIAG_FULL",
                    Name = "Full Diagnostic Suite",
                    Description = "Run all safe diagnostic checks automatically",
                    AutoGenerated = true,
                    Risk = RiskLevel.Safe,
                    Order = 100
                };
                
                foreach (var cap in diagnostics)
                {
                    wf.Steps.Add(new WorkflowStep
                    {
                        CapabilityId = cap.Id,
                        Description = cap.Name
                    });
                }
                
                RegisterWorkflow(wf);
            }
            
            // Auto-generate: USB Repair Pipeline (scan -> repair -> verify)
            var usbScan = _capabilities.FirstOrDefault(c => c.Id == "USBSCAN");
            var usbRepair = _capabilities.FirstOrDefault(c => c.Id == "USBREPAIR");
            var usbVerify = _capabilities.FirstOrDefault(c => c.Id == "USBVERIFY");
            
            if (usbScan != null && usbRepair != null && usbVerify != null &&
                usbScan.Status != FeatureStatus.Unavailable)
            {
                bool canRepair = usbRepair.Status != FeatureStatus.Unavailable;
                bool canVerify = usbVerify.Status != FeatureStatus.Unavailable;
                
                if (canRepair || canVerify)
                {
                    var wf = new Workflow
                    {
                        Id = "AUTO_USB_REPAIR",
                        Name = "USB Repair Pipeline",
                        Description = "Scan, repair, and verify USB configuration",
                        AutoGenerated = true,
                        AdminRequired = usbRepair.AdminRequired,
                        Risk = RiskLevel.Moderate,
                        Order = 101,
                        Steps = new List<WorkflowStep>
                        {
                            new WorkflowStep { CapabilityId = "USBSCAN", Description = "Scan USB configuration" },
                            new WorkflowStep { CapabilityId = "USBREPAIR", Description = "Repair USB restrictions", RequiresConfirmation = true },
                            new WorkflowStep { CapabilityId = "USBVERIFY", Description = "Verify USB access" }
                        }
                    };
                    
                    RegisterWorkflow(wf);
                }
            }
            
            // Auto-generate: Report Pipeline (generate -> export)
            var genReport = _capabilities.FirstOrDefault(c => c.Id == "GENREPORT");
            var jsonExport = _capabilities.FirstOrDefault(c => c.Id == "JSONEXPORT");
            var zipReport = _capabilities.FirstOrDefault(c => c.Id == "ZIPREPORT");
            
            if (genReport != null && jsonExport != null && zipReport != null)
            {
                var wf = new Workflow
                {
                    Id = "AUTO_REPORT_PIPELINE",
                    Name = "Report Pipeline",
                    Description = "Generate report, export JSON, and create ZIP archive",
                    AutoGenerated = true,
                    Risk = RiskLevel.Safe,
                    Order = 102,
                    Steps = new List<WorkflowStep>
                    {
                        new WorkflowStep { CapabilityId = "GENREPORT", Description = "Generate full report" },
                        new WorkflowStep { CapabilityId = "JSONEXPORT", Description = "Export JSON data" },
                        new WorkflowStep { CapabilityId = "ZIPREPORT", Description = "Create ZIP archive" }
                    }
                };
                
                RegisterWorkflow(wf);
            }
        }
        
        // =================================================================
        // CONTEXT STATE
        // =================================================================
        
        public void SetScanResult(bool hadIssues, bool hadRepair)
        {
            _lastScanHadIssues = hadIssues;
            _lastScanHadRepair = hadRepair;
        }
        
        public bool GetLastScanHadIssues() => _lastScanHadIssues;
        public bool GetLastScanHadRepair() => _lastScanHadRepair;
        
        // =================================================================
        // UTILITY
        // =================================================================
        
        private string GetStatusLabel(FeatureStatus status)
        {
            switch (status)
            {
                case FeatureStatus.Ready: return "READY";
                case FeatureStatus.RequiresAdmin: return "REQUIRES ADMIN";
                case FeatureStatus.Unavailable: return "UNAVAILABLE";
                case FeatureStatus.Error: return "ERROR";
                default: return "UNKNOWN";
            }
        }
        
        private void ShowInvalidSelection()
        {
            Console.WriteLine("\nInvalid selection.");
            Console.WriteLine("Please select an option from the menu.");
            DisplayHelper.PauseReturnToMenu();
        }
        
        private void ShowAdminRequired(string featureName)
        {
            Console.WriteLine("\n============================================================");
            Console.WriteLine("                     ACCESS RESTRICTED");
            Console.WriteLine("============================================================");
            Console.WriteLine($"\nFeature: {featureName}");
            Console.WriteLine("\nAdministrator privileges are required for this operation.");
            Console.WriteLine("\n============================================================");
            DisplayHelper.PauseReturnToMenu();
        }
        
        private void ShowUnavailable(string featureName)
        {
            Console.WriteLine("\n============================================================");
            Console.WriteLine("                     UNAVAILABLE");
            Console.WriteLine("============================================================");
            Console.WriteLine($"\nFeature: {featureName}");
            Console.WriteLine("\nThis feature is not available on this system.");
            Console.WriteLine("\n============================================================");
            DisplayHelper.PauseReturnToMenu();
        }
    }
}
